"""nullable password avatar oauth table

Revision ID: 8f6dc4c10cb3
Revises: 0a906acd3b21
Create Date: 2026-04-21 07:22:21.996081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6dc4c10cb3'
down_revision: Union[str, Sequence[str], None] = '0a906acd3b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
